### PR TITLE
Deprecate jQuery-scroller

### PR DESCRIPTION
**Pull request by carlosesilva**

### CODE REVIEW

**Comment by carlosesilva** [comment]
[BU JS Library](https://trello.com/c/8wTGXOUx/16-bu-js-library)

**Review by inderpreet99 — CHANGES_REQUESTED** [review]
Looks good.

Notes:
* Add unit tests if possible for completeness.
* Write up a quick README. And include docs for BU Modal (since this may be the most ideal place for it): http://developer.bu.edu/webteam/developer/libraryframework/wordpress/library/bu-modal/

**Comment by carlosesilva** [comment]
Hi @Adam42, since @inderpreet99 is out would you mind reviewing this pull request for me please?

As per Inder's request, I've added a readme with a link to docs for BU Modal and I've added some unit tests

For the unit tests I ended up modifying the main plugin file a little bit to make it easier to test against but the functionality should still be the same.

Thanks!

**Review by inderpreet99 — APPROVED** [review]

**Comment by inderpreet99** [comment]
Plugin looks professional now. Maybe overly pro, since this way of including shared js/css is an old way of doing things. Newer ways suggest including js/css as part of the modular plugin. Anyhow your work looks great.

I like the split between having the wiki page for BU Modal and the README for bu-js-lib.

**Pull request merged**
